services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
  nginx:
    image: nginx:1.25
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    working_dir: /app
    ports:
      - 80:80
